export const GET_ALL_PROJECTS = "GET_ALL_PROJECTS";
export const GET_ALL_PROJECTS_SUCCESS = "GET_ALL_PROJECTS_SUCCESS";
export const GET_ALL_PROJECTS_FAILURE = "GET_ALL_PROJECTS_FAILURE";
export const GET_ALL_PROJECT_BY_SERVICE = "GET_ALL_PROJECT_BY_SERVICE";
export const GET_ALL_PROJECT_BY_SERVICE_SUCCESS =
  "GET_ALL_PROJECT_BY_SERVICE_SUCCESS";
export const GET_ALL_PROJECT_BY_SERVICE_FAIL =
  "GET_ALL_PROJECT_BY_SERVICE_FAIL";
export const GET_ALL_PROJECT_BY_CATEGORY = "GET_ALL_PROJECT_BY_CATEGORY";
export const GET_ALL_PROJECT_BY_CATEGORY_SUCCESS =
  "GET_ALL_PROJECT_BY_CATEGORY_SUCCESS";
export const GET_ALL_PROJECT_BY_CATEGORY_FAIL =
  "GET_ALL_PROJECT_BY_CATEGORY_FAIL";
export const GET_PROJECT_BY_ID = "GET_PROJECT_BY_ID";
export const GET_PROJECT_BY_ID_SUCCESS = "GET_PROJECT_BY_ID_SUCCESS";
export const GET_PROJECT_BY_ID_FAIL = "GET_PROJECT_BY_ID_FAIL";
export const GET_LATEST_PROJECTS = "GET_LATEST_PROJECTS";
export const GET_LATEST_PROJECTS_SUCCESS = "GET_LATEST_PROJECTS_SUCCESS";
export const GET_LATEST_PROJECTS_FAIL = "GET_LATEST_PROJECTS_FAIL";
